### ISSUE TITLE
ShchevelevaYA Неверно указан автор предыдущего коммита

### ISSUE THREAD

**Issue by dmieter** [dmieter/os-labs#110]
Неверно указан автор предыдущего коммита
`ShchevelevaYA, EShcheveleva, A-06-21, REVNBleach, "Resolved merge conflict in students.txt", 23b5ecbcea65b0afea22adc07cec7e1e523b0aae`

**Comment by EShcheveleva** [comment]
Добрый день, Дмитрий Михайлович. 

Не увидела что вы мне ответили на таску, так что поздно среагировала. Сейчас исправила `ShchevelevaYA, EShcheveleva, A-06-21, [AleksNot007], "Resolved merge conflict i>`

С уважением, студентка группы А-06-21 Щевелева Елена

**Comment by dmieter** [comment]
Принято!
