### ISSUE TITLE
Сделал лаб 2

### ISSUE THREAD

**Issue by MShverdiakov** [dmieter/os-labs#123]
https://github.com/MShverdiakov/OS-labs/

**Comment by dmieter** [comment]
Диапазон номеров строк выглядит неверно:
https://github.com/MShverdiakov/OS-labs/blob/main/lab-2/step_4.txt
821 - 1409

**Comment by MShverdiakov** [comment]
Неправильно прочитал задание, вывел диапазон вхождений моей почты в тексте (1 упоминание - последнее упоминание)
Исправил на диапазон задания
