### ISSUE TITLE
ZavyalovGA необходимо исправить мерж конфликт

### ISSUE THREAD

**Issue by dmieter** [dmieter/os-labs#126]
Необходимо исправить мерж конфликт из этого коммита:
https://github.com/dmieter/os-labs/commit/fff911f3d560dfc464aa4cec7d1114cd7bfd13fc
![Screenshot from 2024-09-26 15-35-58](https://github.com/user-attachments/assets/f4fa2f73-cab8-41af-b740-2ff8ca48de5c)

**Comment by Grisha159-pixel** [comment]
Исправил
