### ISSUE TITLE
Сделал лаб1 Ларин А-09-21

### ISSUE THREAD

**Issue by Fructerrr** [dmieter/os-labs#127]

**Comment by dmieter** [comment]
Неверно указан автор коммита a16315c1b4e564c8bc79c0048bbeb3cc5f6b4704
`LarNikA, Fructerrr, A-09-21, xvxmiii, "Исправлен конфликт слияния", a16315c1b4e564c8bc79c0048bbeb3cc5f6b4704`

**Comment by Fructerrr** [comment]
Исправил ошибку

**Comment by dmieter** [comment]
принято
