### ISSUE TITLE
LR1 Putitye

### ISSUE THREAD

**Issue by Jayson3xxz** [dmieter/os-labs#148]
Putitye

**Comment by dmieter** [comment]
Необходимо добавить данные согласно пункту 1 задания
https://github.com/dmieter/os-labs/tree/main/labs-2024/lab1

**Comment by Jayson3xxz** [comment]
Добрый вечер, исправил, согласно замечаниям

вт, 8 окт. 2024 г. в 15:17, dmieter ***@***.***>:

**Comment by dmieter** [comment]
Выслал приглашение
