### ISSUE TITLE
SorokinArO неверный ID коммита

### ISSUE THREAD

**Issue by dmieter** [dmieter/os-labs#155]
Приведенный коммит https://github.com/dmieter/os-labs/commit/259f69946a44c118ed99be2dda2716fa637356aa не относится к файлу students.txt
`SorokinArO, Jayson3xxz, A-09-21, matvma, "Message", 259f69946a44c118ed99be2dda2716fa637356aa`

**Comment by Jayson3xxz** [comment]
Исправил, теперь в файле номер предыдущего коммита

**Comment by dmieter** [comment]
Принято
