### ISSUE TITLE
Хачу права, чтобы добавить свой txt файл

### ISSUE THREAD

**Issue by makor1dze** [dmieter/os-labs#27]
Я, Макаров Данил, староста группы А-09-19, прошу предоставить мне права для добавления своего txt файла в Ваш репозиторий. Хочу выполнить ЛР1 по ОС :(

Юзернейм на GitHub: makor1dze
Ссылка на созданный репозиторий: https://github.com/makor1dze/for_OS_labs
Мой статус вконтакте: Ekrosvel Gang
Мой любимый цвет - коричневый
Знак зодиака - Лев

**Comment by Evgenyan1488** [comment]
Извините, Макаров Данил, но вам отказано в доступе, по причине: alabay

**Comment by dmieter** [comment]
Заявка рассмотрена успешно, инвайт выслал.
