### ISSUE TITLE
Lab1- Aleksandr-Krivosheev 

### ISSUE THREAD

**Issue by Aleksandr-Krivosheev** [dmieter/os-labs#53]
https://github.com/Aleksandr-Krivosheev/OS-Labs
Aleksandr-Krivosheev

**Comment by dmieter** [comment]
Добавьте имя пользователя

**Comment by Aleksandr-Krivosheev** [comment]
Aleksandr-Krivosheev

**Comment by dmieter** [comment]
Спасибо, выслал инвайт
