### ISSUE TITLE
Исправления для GrIvans

### ISSUE THREAD

**Issue by dmieter** [dmieter/os-labs#80]
Необходимо исправить строчку согласно заданию:

`Грибков Иван Сергеевич, GrIvans, А-06-21, "first commit in 2024/2025", 759049982be920e88e7652ef1b5adf297483e71b`

1) **ваше имя ОСЭП МЭИ**, 2) ваш юзернейм на github 3) номер группы, 4) **юзернейм пользователя, который сделал последний (предыдущий перед вами) коммит** файла students.txt 5)сообщение предыдущего коммита 6) id предыдущего коммита.

**Comment by GrIvans** [comment]
Исправил строку в [этом коммите](https://github.com/dmieter/os-labs/commit/085c2182b6fd983a537c07bdaa4eb4a559cc175c).

**Comment by dmieter** [comment]
Спасибо, принято!
