### ISSUE TITLE
Исправления для IlsafSh

### ISSUE THREAD

**Issue by dmieter** [dmieter/os-labs#81]
Необходимо исправить строчку согласно заданию:
`Шарибжанов Илсаф Тагирович, IlsafSh, Аэ-21-21, "Something important.."`

напишите **ваше имя ОСЭП МЭИ**, юзернейм, номер группы и доброе приветственное сообщение всем остальным студентам.

**Comment by IlsafSh** [comment]
Исправлено

**Comment by dmieter** [comment]
Спасибо, принято!
