### ISSUE TITLE
Popov-Dmitriy-Ivanovich

### ISSUE THREAD

**Issue by Popov-Dmitriy-Ivanovich** [dmieter/os-labs#96]
github username: Popov-Dmitriy-Ivanovich
https://github.com/Popov-Dmitriy-Ivanovich/OS-LABS

**Comment by dmieter** [comment]
Необходимо указать имя пользователя

**Comment by dmieter** [comment]
Выслал приглашение (ожидал, что вы напишете комментарий или переназначите тикет обратно на меня)
