### ISSUE TITLE
IsmailovaAD неверное сообщение коммита

### ISSUE THREAD

**Issue by dmieter** [dmieter/os-labs#99]
Поясните, пожайлуйста, откуда было взято сообщение _omg, done_ для строчки:
`IsmailovaAD, Aleks_not007,Ae-21-21, tarki01, "omg, done",1836309b44961ca59c3d325f656b3275e5a615a2`
На первый взгляд выглядит неверно

**Comment by AleksNot007** [comment]
Исправила
